version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "14:45"
    timezone: Asia/Manila
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: friday
    time: "14:45"
    timezone: Asia/Manila
  open-pull-requests-limit: 10
