queue_rules:
  - name: default
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=verify
      - author~=^edgedalmacio$
      - status-success=verify
      - label=ready-to-merge
      - author~=^edgedalmacio$
      - status-success=verify
      - label=merge-on-weekend
      - schedule=Sat-Sun 08:00-16:00[Asia/Manila]
    conditions:
      - status-success=verify
    merge_method: rebase

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
