queue_rules:
  # Queue for ready-to-merge PRs from maintainer
  - name: ready-to-merge
    queue_conditions:
      - status-success=verify
      - author~=^edgedalmacio$
      - label=ready-to-merge
    merge_conditions:
      - status-success=verify
      - base=master
    merge_method: rebase

  # Queue for weekend merges from maintainer  
  - name: merge-on-weekend
    queue_conditions:
      - status-success=verify
      - author~=^edgedalmacio$
      - label=merge-on-weekend
      - schedule=Sat-Sun 08:00-16:00[Asia/Manila]
    merge_conditions:
      - status-success=verify
      - base=master
    merge_method: rebase

  # Queue for Dependabot PRs
  - name: dependabot
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=verify
    merge_conditions:
      - status-success=verify
      - base=master
    merge_method: rebase

pull_request_rules:
  # Automatically queue qualifying PRs
  - name: auto-queue qualifying PRs
    conditions:
      - or:
          # Dependabot PRs that pass verification
          - and:
              - author~=^dependabot(|-preview)\[bot\]$
              - status-success=verify
          # Maintainer PRs with ready-to-merge label
          - and:
              - author~=^edgedalmacio$
              - label=ready-to-merge
              - status-success=verify
          # Maintainer PRs with weekend merge label (during weekend hours)
          - and:
              - author~=^edgedalmacio$
              - label=merge-on-weekend
              - status-success=verify
              - schedule=Sat-Sun 08:00-16:00[Asia/Manila]
    actions:
      queue:

priority_rules:
  # Highest priority for ready-to-merge
  - name: priority ready-to-merge
    conditions:
      - author~=^edgedalmacio$
      - label=ready-to-merge
    priority: 3000

  # Medium priority for weekend merges
  - name: priority weekend-merge
    conditions:
      - author~=^edgedalmacio$
      - label=merge-on-weekend
      - schedule=Sat-Sun 08:00-16:00[Asia/Manila]
    priority: 2000

  # Lower priority for Dependabot
  - name: priority dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    priority: 1000
