queue_rules:
  - name: default
    conditions:
      - check-success=Travis CI - Pull Request

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Travis CI - Pull Request
    actions:
      queue:
        method: rebase
        name: default

  - name: automatic merge for ready-to-merge pull requests
    conditions:
      - author~=^edgedalmacio$
      - status-success=Travis CI - Pull Request
      - label=ready-to-merge
    actions:
      queue:
        method: rebase
        name: default
