queue_rules:
  - name: default
    conditions:
      - status-success=verify

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=verify
    actions:
      queue:
        method: rebase
        name: default

  - name: automatic merge for ready-to-merge pull requests
    conditions:
      - author~=^edgedalmacio$
      - status-success=verify
      - label=ready-to-merge
    actions:
      queue:
        method: rebase
        name: default

  - name: automatic merge for merge-on-weekend pull requests
    conditions:
      - author~=^edgedalmacio$
      - status-success=verify
      - label=merge-on-weekend
      - schedule=Sat-Sun 08:00-16:00[Asia/Manila]
    actions:
      queue:
        method: rebase
        name: default
