# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy phisix-2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.PHISIX_2_KEY }}'
    - name: Test Deploy
      run: mvn -B clean package appengine:deploy -Pphisix-2 --file pom.xml
