# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Close stale issues and pull requests

on:
  schedule:
    # Run daily at 1:30 AM UTC (9:30 AM Manila time)
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
        # Stale configuration
        days-before-stale: 30
        days-before-close: 7
        
        # Labels
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        
        # Exempt labels - issues and PRs with these labels will never be marked stale
        exempt-issue-labels: 'work-in-progress,pinned,security,bug,enhancement,good first issue'
        exempt-pr-labels: 'work-in-progress,dependencies,security,review-required'
        
        # Messages
        stale-issue-message: |
          This issue has been automatically marked as stale because it has been open for 30 days with no activity.
          
          If this issue is still relevant, please:
          - Add a comment to remove the stale label
          - Provide additional information or updates
          
          This issue will be closed automatically in 7 days if no further activity occurs.
          Thank you for your contributions! 🙏
          
        stale-pr-message: |
          This pull request has been automatically marked as stale because it has been open for 30 days with no activity.
          
          If this PR is still being worked on, please:
          - Add a comment to remove the stale label
          - Push new commits or updates
          - Request review if ready
          
          This PR will be closed automatically in 7 days if no further activity occurs.
          Thank you for your contributions! 🙏
          
        close-issue-message: |
          This issue was automatically closed because it has been stale for 7 days with no activity.
          
          If you believe this issue should remain open, please:
          - Reopen the issue
          - Provide additional context or updates
          - Remove the stale label
          
          Thank you for your understanding! 🙏
          
        close-pr-message: |
          This pull request was automatically closed because it has been stale for 7 days with no activity.
          
          If you want to continue working on this PR, please:
          - Reopen the pull request
          - Address any feedback or conflicts
          - Remove the stale label
          
          Thank you for your contributions! 🙏
          
        # Operations limit to avoid hitting GitHub API rate limits
        operations-per-run: 50
        
        # Remove stale label when issues/PRs are updated
        remove-stale-when-updated: true
        
        # Enable statistics in logs
        enable-statistics: true
